version: '2'
networks:
  sensu:
    driver: bridge
services:
  redis:
    image: redis:3.2.4
    container_name: redis
    ports: [ "6379:6379" ]
    networks: ["sensu"]
  sensu-server:
    image: server
    container_name: sensu-server
    networks: ["sensu"]
    build:
      context: server
    volumes:
      - "./config:/etc/sensu"
  sensu-api:
    image: api
    container_name: sensu-api
    networks: ["sensu"]
    build:
      context: api
    ports: [ "4567:4567" ]
    volumes:
      - "./config:/etc/sensu"
  uchiwa:
    image: uchiwa/uchiwa
    container_name: uchiwa
    networks: ["sensu"]
    ports: [ "3000:3000" ]
    volumes:
      - "./uchiwa-config:/config"
  sensu-client:
    image: dronedeploy/sensu-client
    container_name: sensu-client
    networks: ["sensu"]
    build:
      context: client
    volumes:
      - "./config:/etc/sensu"
